### ISSUE TITLE
Design interface mechanism between Unity DAPA and SDAP deployed in MCP/EKS

### ISSUE THREAD

**Issue by jjacob7734** [unity-sds/unity-analytics#38]

**Comment by mike-gangl** [comment]
please add the design artifacts and close the ticket if this is done.

**Comment by jjacob7734** [comment]
@zx128 created the OpenAPI design in https://github.com/unity-sds/unity-analytics-dapa/blob/devel/doc/openapi.yaml. He checked in the OpenAPI stub code for the SDAP time series DAPA interface here: https://github.com/unity-sds/unity-analytics-dapa/tree/devel.  The empty implementation is in the `controllers` directory and points to our functions in the `support` directory.
