### ISSUE TITLE
Create papermilled notebook of example BCDP execution.

### ISSUE THREAD

**Issue by jjacob7734** [unity-sds/unity-analytics#4]

**Comment by jjacob7734** [comment]
Inputs to the notebook need to be moved to their own cell near the top of the notebook.  That cell needs to be tagged with `parameters`.  Papermill will substitute values for these parameters at run-time, so in the notebook the input variables should be assigned default values with the expectation that the values will change with each run.

**Comment by jjacob7734** [comment]
An example Papermilled notebook is https://github.com/pymonger/downsample-landsat/blob/main/downsample_landsat.ipynb.

**Comment by agoodm** [comment]
Example notebook has been placed in https://github.com/unity-sds/unity-analytics-bcdp/blob/main/cordex_example_papermill.ipynb, so I will now close.
